import Vue from 'vue'
import { Button, Loading, Overlay, Form, Field, Notify, Toast, Tabbar, TabbarItem, Image, Icon, Swipe, SwipeItem, NavBar, Badge, CellGroup, Cell, Empty, PullRefresh, Tabs, Tab, Tag, Popup, RadioGroup, Radio, Checkbox, ActionSheet, DatetimePicker, IndexBar, IndexAnchor } from 'vant'

export default function () {
  Vue.use(Button)
    .use(Loading)
    .use(Overlay)
    .use(Form)
    .use(Field)
    .use(Notify)
    .use(Toast)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Image)
    .use(Icon)
    .use(Swipe)
    .use(SwipeItem)
    .use(NavBar)
    .use(Badge)
    .use(CellGroup)
    .use(Cell)
    .use(Empty)
    .use(PullRefresh)
    .use(Tabs)
    .use(Tab)
    .use(Tag)
    .use(Popup)
    .use(RadioGroup)
    .use(Radio)
    .use(Checkbox)
    .use(ActionSheet)
    .use(DatetimePicker)
    .use(IndexBar)
    .use(IndexAnchor)
}
